// Generated by CoffeeScript 1.6.1
(function() {
  var _;

  global.Backend = require("../classes/backend");

  global.Restfull = require("../classes/restfull");

  global.User = require("../classes/user");

  _ = require("lodash");

  global.beforeEachTest = function() {
    return this.addMatchers({
      toBeFunction: function() {
        return _.isFunction(this.actual);
      },
      toBeJson: function(obj) {
        if (obj) {
          return JSON.stringify(this.actual) === JSON.stringify(obj);
        } else {
          return {}.toString.call(this.actual) === "[object Object]";
        }
      },
      toBeArray: function() {
        return this.actual.length !== void 0;
      },
      toBeInstanceOf: function(obj) {
        return this.actual instanceof obj;
      }
    });
  };

}).call(this);
