// Generated by CoffeeScript 1.6.1
(function() {
  var i, k, p, rest, user, _i;

  require("./globals");

  rest = new Restfull;

  for (i = _i = 1; _i <= 10; i = ++_i) {
    user = new User("User_" + i);
    p = user.create();
    k = i - 1;
    p.done(function(data) {
      return console.log("" + k + " added");
    });
    p.error(function() {
      return console.log("error", arguments);
    });
  }

  p = rest.get(["operator"]);

  p.done(function(data) {
    return console.log(data);
  });

  p.error(function() {
    return console.log("error", arguments);
  });

  p = rest["delete"](["operator"]);

  p.done(function(data) {
    console.log(data);
    p = rest.post(["index"], {
      login: "root",
      password: "123Vjq123"
    });
    p.done(function(data) {
      console.log(data);
      p = rest.post(["index", "root"], {
        password: "123Vjq123"
      });
      p.done(function(data) {
        console.log(data);
        p = rest.get(["user"], {
          limit: 3,
          skip: 4
        });
        p.done(function(data) {
          return console.log(data);
        });
        return p.error(function() {
          return console.log("no users?", arguments);
        });
      });
      return p.error(function() {
        return console.log("error?", arguments);
      });
    });
    return p.error(function() {
      return console.log("error", arguments);
    });
  });

  p.error(function() {
    return console.log("error", arguments);
  });

}).call(this);
