// Generated by CoffeeScript 1.3.3
(function() {
  var p, rest;

  require("./globals");

  rest = new Restfull;

  p = rest.get(["operator"]);

  p.done(function(data) {
    return console.log(data);
  });

  p.error(function() {
    return console.log("error", arguments);
  });

  p = rest["delete"](["operator"]);

  p.done(function(data) {
    console.log(data);
    p = rest.post(["index"], {
      login: "root",
      password: "123Vjq123"
    });
    p.done(function(data) {
      console.log(data);
      p = rest.post(["index", "root"], {
        password: "123Vjq123"
      });
      p.done(function(data) {
        console.log(data);
        p = rest.get(["user"], {
          limit: 10,
          skip: 0
        });
        p.done(function(data) {
          return console.log(data);
        });
        return p.error(function() {
          return console.log("no users?", arguments);
        });
      });
      return p.error(function() {
        return console.log("error?", arguments);
      });
    });
    return p.error(function() {
      return console.log("error", arguments);
    });
  });

  p.error(function() {
    return console.log("error", arguments);
  });

}).call(this);
