// Generated by CoffeeScript 1.6.2
(function() {
  var Auth;

  Auth = (function() {
    function Auth(rest) {
      this.rest = rest;
    }

    Auth.prototype.login = function(callbacks) {
      var p,
        _this = this;

      p = this.rest.get("index");
      p.error(callbacks.fail);
      return p.done(function(data) {
        if (data && data.whois) {
          _this.whois = data.whois;
          _this.group = data.group;
          return callbacks.ok();
        } else {
          return callbacks.fail();
        }
      });
    };

    return Auth;

  })();

  module.exports = Auth;

}).call(this);
