// Generated by CoffeeScript 1.6.1
(function() {
  var Backend, isArray;

  isArray = Array.isArray || function(value) {
    return {}.toString.call(value) === '[object Array]';
  };

  Backend = (function() {

    function Backend(prefix) {
      this.prefix = prefix != null ? prefix : "/api";
      this.authenticatedAs = 'guest';
      this.mockDB = {};
    }

    Backend.prototype._saveLastRequest = function(method, url, data) {
      if (isArray(url)) {
        url = url.join("/");
      }
      this.lastRequest = {
        method: method,
        url: "" + this.prefix + "/" + url,
        data: data
      };
      return false;
    };

    Backend.prototype._urlPartify = function(url) {
      if (!isArray(url)) {
        return url.split('/');
      } else {
        return url;
      }
    };

    Backend.prototype._withId = function(id, entity, data, withId, withoutId) {
      if (!id) {
        return withoutId.apply(this, [entity, data]);
      } else {
        return withId.apply(this, [entity, id, data]);
      }
    };

    Backend.prototype.getWithoutId = function(entity, data) {
      var limit, res, skip, skiplimitsum;
      skip = data.skip;
      delete data.skip;
      limit = data.limit;
      delete data.limit;
      skiplimitsum = skip + limit;
      if (!skiplimitsum) {
        skiplimitsum = void 0;
      }
      res = this.mockDB[entity].filter(function(obj) {
        var flag, k, v;
        flag = true;
        for (k in data) {
          v = data[k];
          if (obj[k] !== v) {
            flag = false;
            break;
          }
        }
        return flag;
      });
      return res.slice(skip, skiplimitsum).reverse();
    };

    Backend.prototype.getWithId = function(entity, id, data) {
      var obj, _i, _len, _ref;
      if (this.mockDB[entity]) {
        _ref = this.mockDB[entity];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          obj = _ref[_i];
          if (String(obj.id) === id) {
            return obj;
          }
        }
      }
    };

    Backend.prototype.putWithoutId = function(entity, data) {
      return false;
    };

    Backend.prototype.putWithId = function(entity, id, data) {
      var k, obj, v, _i, _len, _ref;
      if (this.mockDB[entity]) {
        _ref = this.mockDB[entity];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          obj = _ref[_i];
          if (!(String(obj.id) === id)) {
            continue;
          }
          for (k in data) {
            v = data[k];
            obj[k] = v;
          }
          return true;
        }
        data.id = id;
        this.mockDB[entity].push(data);
        return true;
      }
    };

    Backend.prototype.postWithoutId = function(entity, data) {
      var maxid, obj, _i, _len, _ref;
      if (this.mockDB[entity]) {
        maxid = 0;
        _ref = this.mockDB[entity];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          obj = _ref[_i];
          if (maxid < obj.id) {
            maxid = obj.id;
          }
        }
        maxid += 1;
        data.id = maxid;
        this.mockDB[entity].push(data);
        return [entity, "" + maxid];
      }
    };

    Backend.prototype.postWithId = function(entity, id, data) {
      return false;
    };

    Backend.prototype.deleteWithoutId = function(entity, data) {
      this.mockDB[entity] = [];
      return true;
    };

    Backend.prototype.deleteWithId = function(entity, id, data) {
      if (this.mockDB[entity]) {
        this.mockDB[entity] = this.mockDB[entity].filter(function(obj) {
          return String(obj.id) !== id;
        });
        return true;
      }
    };

    Backend.prototype.get = function(url, data) {
      var entity, id, _ref;
      if (url == null) {
        url = "";
      }
      if (data == null) {
        data = {};
      }
      this._saveLastRequest("get", url, data);
      _ref = this._urlPartify(url), entity = _ref[0], id = _ref[1];
      return this._withId(id, entity, data, this.getWithId, this.getWithoutId);
    };

    Backend.prototype.put = function(url, data) {
      var entity, id, _ref;
      if (url == null) {
        url = "";
      }
      if (data == null) {
        data = {};
      }
      this._saveLastRequest("put", url, data);
      _ref = this._urlPartify(url), entity = _ref[0], id = _ref[1];
      return this._withId(id, entity, data, this.putWithId, this.putWithoutId);
    };

    Backend.prototype.post = function(url, data) {
      var entity, id, _ref;
      if (url == null) {
        url = "";
      }
      if (data == null) {
        data = {};
      }
      this._saveLastRequest("post", url, data);
      _ref = this._urlPartify(url), entity = _ref[0], id = _ref[1];
      return this._withId(id, entity, data, this.postWithId, this.postWithoutId);
    };

    Backend.prototype["delete"] = function(url, data) {
      var entity, id, _ref;
      if (url == null) {
        url = "";
      }
      if (data == null) {
        data = {};
      }
      this._saveLastRequest("delete", url, data);
      _ref = this._urlPartify(url), entity = _ref[0], id = _ref[1];
      return this._withId(id, entity, data, this.deleteWithId, this.deleteWithoutId);
    };

    return Backend;

  })();

  module.exports = Backend;

}).call(this);
