// Generated by CoffeeScript 1.6.1
(function() {
  var Cpanel;

  global.Restfull = require("../classes/restfull");

  global.User = require("../classes/user");

  Cpanel = (function() {

    function Cpanel() {
      var _this = this;
      this.rest = new Restfull;
      this.authenticated({
        ok: function() {
          return _this.showOperatorLogin();
        },
        fail: function() {
          return _this.redirectToLogin();
        }
      });
      $(document).ready(function() {
        console.log("bga test");
        return $('#operator_logoff').click(function() {
          console.log(_this);
          return _this.logoff();
        });
      });
    }

    Cpanel.prototype.authenticated = function(callbacks) {
      var p,
        _this = this;
      p = this.rest.get("index");
      p.error(callbacks.fail);
      return p.done(function(data) {
        if (data && data.whois) {
          _this.whois = data.whois;
          _this.group = data.group;
          return callbacks.ok();
        } else {
          return callbacks.fail();
        }
      });
    };

    Cpanel.prototype.redirectToLogin = function() {
      return global.location = "login.html";
    };

    Cpanel.prototype.showOperatorLogin = function() {
      return $('#operator_login_content').text("@" + this.whois);
    };

    Cpanel.prototype.logoff = function() {
      var p,
        _this = this;
      p = this.rest["delete"]("index");
      return p.done(function() {
        return _this.redirectToLogin();
      });
    };

    return Cpanel;

  })();

  module.exports = Cpanel;

}).call(this);
