// Generated by CoffeeScript 1.6.2
(function() {
  var Geoip,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Geoip = (function() {
    function Geoip(handler, url) {
      this.handler = handler;
      this.url = url != null ? url : "http://ru.smart-ip.net/geoip-json?lang=ru";
      this.callback = __bind(this.callback, this);
      $.ajax({
        url: this.url,
        dataType: "jsonp",
        success: this.callback
      });
    }

    Geoip.prototype.callback = function(data) {
      console.log(data);
      this.country = data.countryName;
      this.city = data.city;
      return this.handler({
        country: this.country,
        city: this.city
      });
    };

    return Geoip;

  })();

  module.exports = Geoip;

}).call(this);
