// Generated by CoffeeScript 1.6.1
(function() {
  var Restfull,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Restfull = (function(_super) {

    __extends(Restfull, _super);

    function Restfull() {
      return Restfull.__super__.constructor.apply(this, arguments);
    }

    return Restfull;

  })(Backend);

  module.exports = Restfull;

}).call(this);
