// Generated by CoffeeScript 1.6.1
(function() {
  var User;

  User = (function() {

    function User(name, surname, patronymic, participant, status) {
      this.name = name != null ? name : "";
      this.surname = surname != null ? surname : "";
      this.patronymic = patronymic != null ? patronymic : "";
      this.participant = participant != null ? participant : "";
      this.status = status != null ? status : "new";
      this.backend = new Restfull;
    }

    User.prototype.create = function() {
      var url;
      url = this.backend.post("user", {
        name: this.name,
        surname: this.surname,
        patronymic: this.patronymic,
        participant: this.participant,
        status: this.status
      });
      this.id = parseInt(url[1]);
      return true;
    };

    User.prototype.getById = function(id) {
      return this.backend.get(["user", "" + id]);
    };

    User.prototype.list = function() {
      return this.backend.get("user");
    };

    User.prototype.listFiltered = function(skip, limit) {
      var data;
      if (skip == null) {
        skip = void 0;
      }
      if (limit == null) {
        limit = void 0;
      }
      data = {};
      if (this.participant !== void 0) {
        data.participant = this.participant;
      }
      if (this.status !== void 0) {
        data.status = this.status;
      }
      data.skip = skip;
      data.limit = limit;
      return this.backend.get("user", data);
    };

    User.prototype.update = function(id, status) {
      return this.backend.put(["user", String(id)], {
        status: status
      });
    };

    User.prototype.setup = function(backend) {
      this.backend = backend;
    };

    return User;

  })();

  module.exports = User;

}).call(this);
